vich_uploader:
    db_driver: orm

    mappings:
        tip_image:
            uri_prefix: "%upload_directory%"
            upload_destination: "%kernel.project_dir%/public%upload_directory%"
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
